name: Stable Docker images

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker-build:
    strategy:
      matrix:
        runner: [ubicloud-standard-2-ubuntu-2204-arm]
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: generate or hydrate protos
        uses: ./.github/actions/genprotos

      - uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build (optionally publish) PeerDB Images
        uses: depot/bake-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/nexus.Dockerfile
          push: true
          tags: |
            ghcr.io/peerdb-io/peerdb-server:${{ github.ref_name }}

      - name: Publish Flow API Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/flow-api.Dockerfile
          push: true
          tags: |
            ghcr.io/peerdb-io/flow-api:${{ github.ref_name }}

      - name: Publish Flow Worker Stable Image
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_TOKEN }}
          context: .
          file: stacks/flow-worker.Dockerfile
          push: true
          tags: |
            ghcr.io/peerdb-io/flow-worker:${{ github.ref_name }}
